-- MySQL Script generated by MySQL Workbench
-- Fri Nov  6 19:44:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zonas` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Area` VARCHAR(45) NULL,
  `Concejal` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`),
  CONSTRAINT `Contiene`
    FOREIGN KEY (`Nombre`)
    REFERENCES `mydb`.`Calle` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calle` (
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`),
  CONSTRAINT `Pertenece`
    FOREIGN KEY (`Nombre`)
    REFERENCES `mydb`.`Zonas` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Contiene`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Construcción` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Unifamiliar` (
  `Superficie` VARCHAR(45) NOT NULL,
  `Número habitantes` INT NULL,
  PRIMARY KEY (`Superficie`),
  CONSTRAINT `pertenece`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Construcción` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `habita`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Persona` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pertenece`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Persona` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Edad` INT NULL,
  PRIMARY KEY (`DNI`),
  CONSTRAINT `Posee`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Piso` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Posee`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Unifamiliar` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `es cabeza de familia de`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Persona` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `Superficie` VARCHAR(45) NOT NULL,
  `Letra` VARCHAR(45) NULL,
  `Planta` INT NULL,
  PRIMARY KEY (`Superficie`),
  CONSTRAINT `pertenece`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Bloques` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Habita`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Persona` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Pertenece`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Persona` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloques` (
  `Numero` INT NOT NULL,
  PRIMARY KEY (`Numero`),
  CONSTRAINT `Pertenece`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Construcción` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contiene`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Piso` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Construcción`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Construcción` (
  `Número` INT NOT NULL,
  `Coordenadas` INT NULL,
  `Superficie` INT NULL,
  PRIMARY KEY (`Número`),
  CONSTRAINT `está`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Calle` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contiene`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Bloques` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contiene`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Unifamiliar` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
